project:
  type: website
  output-dir: docs

website:
  title: "Mac's Rfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icd.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



