project:
  type: website
  output-dir: docs

website:
  title: "Mac's Rfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: icd.qmd
        text: ICD

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



